name = "PearsonCorrelationMatch"
uuid = "a9b75987-8b2a-4819-9442-b884e853de6b"
version = "1.0.0"
authors = ["Alex Knudson <alexk.706@gmail.com>"]

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Distributions = "0.25"
LinearAlgebra = "1"
julia = "1.10"
